FILE=aws_diagram.py

all: diagram
.PHONY: all

diagram:
	@echo "Creating diagram of the project."
	@python3 "${FILE}"
	@echo "Done."

clean:
	@echo "Removing diagram."
	@rm -f covid19_scraper_web_app.png
	@echo "Removed."
